import Head from "next/head";
import Image from "next/image";
import { useContext, useEffect, useState } from "react";
import Main from "../components/Main";
import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";

import { NotesContext } from "../utils/notesContext";

import { table, minifyItems } from "../utils/airtable";

import auth0 from "../utils/auth0";

const fetcher = (url) => fetch(url).then((res) => res.json());

const Themes = ["light", "cupcake", "dark", "luxury", "retro"];

export default function Home({ initialItems, user }) {
  // const [notes, setNotes] = useState([]);
  // const [activeNoteId, setActiveNoteId] = useState("");

  // const onAddNote = () => {};

  // const onUpdateNote = () => {};

  // const onDeleteNote = () => {};

  // const getActiveNote = () => {
  //   const found1 = notes.filter((note) => note.id === activeNoteId);
  //   const found2 = notes.find((note) => note.id === activeNoteId);

  //   console.log(found1, found2);
  // };

  const { notes, setNotes } = useContext(NotesContext);

  useEffect(() => {
    setNotes(initialItems);
  }, [initialItems]);

  if (!notes) return <div>Loading...</div>;

  return (
    <div className="py-2 mx-4">
      <Head>
        <title>NotesRfun</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar Themes={Themes} user={user} />

        <div className="flex flex-row w-11/12 h-screen overflow-y-auto">
          <div className="w-1/4 border-r border-gray-400 mr-10">
            <Sidebar />
          </div>
          <div className="w-3/4 mr-10">
            <Main />
          </div>
        </div>
      </main>
    </div>
  );
}

export const getServerSideProps = async (ctx) => {
  const session = await auth0.getSession(ctx.req, ctx.res);

  const notes = await table.select().firstPage();

  return {
    props: {
      initialItems: minifyItems(notes),
      user: session?.user || null,
    },
  };
};
